### PR TITLE
Added compatibility with Python 3 and some other improvements

### PR DESCRIPTION
**Pull request by abdel792**
This Pull Request adds the following improvements:

* Adding compatibility with Python 3 and nvda-2019.3;
* Removal of blanks at the beginning and end of text when copying;
* Replacement of indentation to 1 tab rather than 4 spaces.

@jscholes:

What do you think?

Thanks.

### CODE REVIEW

**Comment by jscholes** [comment]
@abdel792 - thank you so much for the work on this, and for submitting a PR.  I haven't yet merged #3, because I'm not convinced that indiscriminately trimming whitespace from text when copying is the right thing to do.  I'm still thinking it through, but at a minimum I need to give users the option of turning it off (and choosing between left/right trimming or both).

With that in mind, if you could revert that portion of the PR, leaving the add-on restructuring, Python 3 compat and indentation changes in place, I'd be happy to merge.

**Comment by abdel792** [comment]
OK @jscholes,

I will review this point and you will send the correction of the PR, probably before the end of the week.

Thanks.

**Comment by abdel792** [comment]
Hey @jscholes,

Done.

The last commit in the py3 branch which is waiting to be merged in master now includes the following additions:

1. Creation of the structure for addonTemplate, the add-on can now be built with the scons command.
2. According to author's request, restoration of the function including the blanks before and after the copied text, now we can choose to include these blanks by pressing F12 once or to delete them by pressing it twice.
3. Update of the documentation and the version as well as the docstring of the script allowing to copy the text of the log.

The download link provided in the readme.md file is not yet functional, it will be when the addonfiles repo at github.com/nvdaaddons is operational.

If you wish, @jscholes, you can request that the add-on repo be added to github.com/nvdaaddons, it is not there yet.

Thanks.

**Comment by jscholes** [comment]
@abdel792, I'm out of the loop and not entirely clear about the current state of add-on builds.  Please advise on the next steps to get this update released and to users as quickly as possible.

**Comment by ultrasound1372** [comment]
So it looks like the way you'd wanna do this is by creating a release over here so you have a binary and then just updating the path in get.php under [addonFiles](https://github.com/nvdaaddons/addonFiles)

**Pull request merged**
