### PR TITLE
Merge all open pull requests and update

### PR DESCRIPTION
**Pull request by ultrasound1372**
This pull request combines #5, #14, and #19 and takes care of the dirty work that such a merge presents. This includes #5's migration to the scons build system for the add-on. It has been tested and confirmed to work on NVDA 2021.1. Merging of this pull request would, therefore, mean that the aforementioned pull requests could be considered resolved and be closed, though #14 might need more testing by @abitglow to confirm that the localization survived the change of build system. If it didn't, please let me know and we can push some commits to make it do so. As with other add-ons, you can now build this one by just typing scons. Or you can get a test build [here](https://github.com/jscholes/nvda-speech-history/files/6810801/speechHistory-2021.1.zip)

### CODE REVIEW

**Comment by jscholes** [comment]
@ultrasound1372 Thank you for submitting.  #19 will be superseded by #21.

**Comment by ultrasound1372** [comment]
@jscholes despite the rather nasty merge involved, this apparently has no conflicts with the base branch. I think we just need someone to test the simplified Chinese localization and then you can merge this and push this out as an update to the add-ons website, which would present it to users of add-on updater. I know this was the one add-on keeping me from upgrading to NVDA 2021.1.

**Comment by jscholes** [comment]
@ultrasound1372 I can't reproduce the issue described in #5, and I don't particularly like the fact that a fix for one issue includes a conversion to the add-on template.  So I've gone ahead and merged #21; I'll release the latest version and then revisit.

**Comment by ultrasound1372** [comment]
@jscholes #5 may have in fact been fixed in later code of yours without realizing, the cases I was using it for actually related to trimming which you've implemented more thoroughly in a way that carried into my fork. I do hope at some point we can move to the add-on template, though, it makes doing builds ourselves much easier to deal with, and allows better localization. But I'll close this since my main thrust for this was to get 2021.1 compatibility which has been achieved in the superseed.

**Pull request closed without merging**
