### PR TITLE
Search dialog

### PR DESCRIPTION
**Pull request by zarvox32**
2021.3 is a huge update for this addon, turning it from a simple barebones script into a well deserved tool.

### CODE REVIEW

**Comment by jscholes** [comment]
@zarvox32 Just so you know, describing existing work on a well-used add-on as a "barebones script" isn't a great start.  It seems like you've made a lot of changes here, but I can't even begin reviewing them without a clear description, in a GitHub comment, of exactly what has been updated and why.  Thank you in advance for providing that when you can.

**Comment by zarvox32** [comment]
@jscholes Thank you for the reply, your response has helped me realize my level of ignorance in an environment such as Git. I have never contributed to someone else's project let alone a whole community, and I was reckless by contributing to this repository completely unprepared. Add to that my extremely unprofessional behavior, and my struggle to use git; I get overwhelmed easily. I dived straight into a strong and well respected community without having any knowledge of etiquette for projects, commits, or communication. And without even reading the NVDA contribution guidelines before making this a serious addition to the speech history addon.
I came here with good intentions, but I understand my first impressions suggest otherwise, and that's on me. My sincere apologies for my inappropriate words and actions. I'm starting on a really bad foot.

**Comment by zarvox32** [comment]
I don't think this poll request is going to work, because I didn't just make one addition, I made several. So I should have made an issue for each separate addition, and if approved, only code that particular feature. So the code I sent has at least 4 individual issues, I know now that's not how this should work. Do you want to close this pr immediately and I can open some issues regarding these changes, or would you like me to redo the commits for this current pr?

**Comment by zarvox32** [comment]
Closed by pr author due to inappropriate git practices.

**Pull request closed without merging**
